### ISSUE TITLE
从房间列表界面返回报错，无法返回

### ISSUE THREAD

**Issue by JasonStrivy** [matchvs/GreedyStar#3]
退出游戏result0
matchvs.all.9de57.js:1 [INFO][Matchvs]  socket on closed ,code:1006(1000:NORMAL,1005:CLOSE_NO_STATUS,1006:RESET,1009:CLOSE_TOO_LARGE) err:{"code":1006,"reason":"error close "}
matchvs.all.9de57.js:1 [INFO][Matchvs]  gateway disconnect
matchvs.all.9de57.js:1 [INFO][Matchvs]  [error code:1001] (1006) gateway network error. network error, please reference [ https://doc.matchvs.com/ErrCode ]
project.dev.48ca9.js:1427 发生错误了！！！

**Comment by fluttergo** [comment]
属于掉线.可能是切后台引起
